In [1]:
import requests
import pandas
from bs4 import BeautifulSoup

In [2]:
def getUrl(team, season):
    return f'https://www.basketball-reference.com/teams/{team}/{season}.html'

In [3]:
url = getUrl("BRK", "2024")
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [4]:
print(url)

https://www.basketball-reference.com/teams/BRK/2024.html

In [5]:
#print(soup)

In [6]:
table = soup.find('table', attrs={"id":"per_game_stats"})
# <div class="table_container tabbed current is_setup" id="div_per_game_stats">
# print(table)

In [7]:
stats_titles = table.find_all('th')
stats_table_titles = [ titles.text.strip() for titles in stats_titles[:30] ]

In [8]:
df = pandas.DataFrame(columns=stats_table_titles)

df

Empty DataFrame
Columns: [Rk, Player, Age, Pos, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Awards]
Index: []

[0 rows x 30 columns]

In [9]:
stats_columns = table.find_all('tr')

for stats_row in stats_columns[1:]:
    row_data = stats_row.find_all('td')
    rank_data = stats_row.find_all('th')

    rank = [ data.text.strip() for data in rank_data ]
    stats = [ data.text.strip() for data in row_data ]
    stats.insert(0, rank[0])

    df.loc[len(df)] = stats

In [10]:
df

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1,Mikal Bridges,27,SF,82,82,34.8,6.9,15.8,.436,...,0.8,3.7,4.5,3.6,1.0,0.4,2.0,1.4,19.6,
1,2,Dennis SchrÃ¶der,30,PG,29,25,32.0,5.4,12.7,.424,...,0.6,2.9,3.5,6.0,0.6,0.3,2.4,2.0,14.6,
2,3,Cam Thomas,22,SG,66,51,31.4,8.0,18.0,.442,...,0.4,2.8,3.2,2.9,0.7,0.2,1.9,2.1,22.5,
3,4,Spencer Dinwiddie,30,PG,48,48,30.7,4.1,10.4,.391,...,0.5,2.8,3.3,6.0,0.8,0.2,1.3,1.8,12.6,
4,5,Nic Claxton,24,C,71,71,29.8,5.2,8.2,.629,...,2.7,7.2,9.9,2.1,0.6,2.1,1.3,2.5,11.8,
5,6,Dorian Finney-Smith,30,PF,68,56,28.4,3.2,7.5,.421,...,1.6,3.1,4.7,1.6,0.8,0.6,0.9,2.2,8.5,
6,7,Cameron Johnson,27,PF,58,47,27.6,4.8,10.7,.446,...,0.9,3.4,4.3,2.4,0.8,0.3,1.0,1.8,13.4,
7,8,Royce O'Neale,30,SF,49,6,24.5,2.6,6.6,.388,...,0.8,3.7,4.5,2.8,0.7,0.6,1.0,2.4,7.4,
8,9,Ben Simmons,27,PG,15,12,23.9,2.9,4.9,.581,...,2.1,5.9,7.9,5.7,0.8,0.6,1.8,2.4,6.1,
9,10,Dennis Smith Jr.,26,PG,56,2,18.9,2.6,6.0,.435,...,0.9,2.0,2.9,3.6,1.2,0.2,1.2,2.2,6.6,
10,11,Lonnie Walker IV,25,SG,58,0,17.4,3.6,8.5,.423,...,0.2,2.0,2.2,1.3,0.6,0.3,0.9,1.2,9.7,
11,12,Noah Clowney,19,PF,23,4,16.1,2.2,4.0,.538,...,1.1,2.4,3.5,0.8,0.3,0.7,0.7,1.1,5.8,
12,13,Jalen Wilson,23,PF,43,3,15.4,1.8,4.2,.425,...,1.1,2.0,3.0,1.0,0.3,0.1,0.4,1.1,5.0,
13,14,Day'Ron Sharpe,22,C,61,1,15.1,2.8,4.8,.571,...,2.6,3.7,6.4,1.4,0.4,0.7,1.1,2.1,6.8,
14,15,Trendon Watford,23,PF,63,2,13.6,2.6,4.9,.527,...,0.8,2.3,3.1,1.3,0.4,0.3,1.0,1.7,6.9,
15,16,Keon Johnson,21,SG,5,0,12.2,1.6,4.2,.381,...,0.6,0.8,1.4,0.6,0.6,0.2,1.0,1.0,6.2,
16,17,Dariq Whitehead,19,SF,2,0,12.0,0.5,2.5,.200,...,0.0,2.0,2.0,1.5,0.0,0.5,0.0,0.0,1.5,
17,18,Jacob Gilyard,25,PG,4,0,11.3,0.0,1.5,.000,...,0.3,0.5,0.8,1.5,1.5,0.0,0.3,1.0,0.0,
18,19,Armoni Brooks,25,PG,10,0,10.4,1.5,4.6,.326,...,0.7,1.1,1.8,0.5,0.1,0.1,0.3,0.3,4.2,
19,20,Harry Giles,25,C,16,0,5.1,1.4,2.8,.500,...,0.8,0.9,1.6,0.4,0.1,0.2,0.4,0.9,3.4,
20,21,Keita Bates-Diop,28,SF,14,0,4.9,0.6,1.1,.500,...,0.1,0.6,0.6,0.3,0.2,0.1,0.1,0.1,1.6,
21,,Team Totals,,,82,82,241.5,40.7,89.1,.456,...,11.4,32.6,44.1,25.6,6.8,5.2,13.1,18.5,110.4,

In [11]:
#df.to_csv(r'C:\Users\jadri\OneDrive\Documents\CSV\Basket.csv', index=False)