In [97]:
import requests
import pandas
from bs4 import BeautifulSoup

In [98]:
def getUrl(team, season):
    return f'https://www.basketball-reference.com/teams/{team}/{season}.html'

In [99]:
url = getUrl("BOS", "2024")
page = requests.get(url)
soup = BeautifulSoup(page.text, 'html')

In [100]:
print(url)

https://www.basketball-reference.com/teams/BOS/2024.html

In [101]:
#print(soup)

In [102]:
table = soup.find('table', attrs={"id":"per_game_stats"})
# <div class="table_container tabbed current is_setup" id="div_per_game_stats">
# print(table)

In [103]:
stats_titles = table.find_all('th', attrs={"scope":"col"})
stats_table_titles = [ titles.text.strip() for titles in stats_titles ]
# print(stats_table_titles)

In [104]:
df = pandas.DataFrame(columns=stats_table_titles)

df

Empty DataFrame
Columns: [Rk, Player, Age, Pos, G, GS, MP, FG, FGA, FG%, 3P, 3PA, 3P%, 2P, 2PA, 2P%, eFG%, FT, FTA, FT%, ORB, DRB, TRB, AST, STL, BLK, TOV, PF, PTS, Awards]
Index: []

[0 rows x 30 columns]

In [105]:
stats_columns = table.find_all('tr')

for stats_row in stats_columns[1:]:
    row_data = stats_row.find_all('td')
    rank_data = stats_row.find_all('th')

    rank = [ data.text.strip() for data in rank_data ]
    stats = [ data.text.strip() for data in row_data ]
    stats.insert(0, rank[0])

    df.loc[len(df)] = stats

In [106]:
df

,Rk,Player,Age,Pos,G,GS,MP,FG,FGA,FG%,...,ORB,DRB,TRB,AST,STL,BLK,TOV,PF,PTS,Awards
0,1,Jayson Tatum,25,PF,74,74,35.7,9.1,19.3,.471,...,0.9,7.2,8.1,4.9,1.0,0.6,2.5,2.0,26.9,"MVP-6,CPOY-9,AS,NBA1"
1,2,Jaylen Brown,27,SF,70,70,33.5,9.0,17.9,.499,...,1.2,4.3,5.5,3.6,1.2,0.5,2.4,2.6,23.0,AS
2,3,Jrue Holiday,33,PG,69,69,32.8,4.8,10.0,.480,...,1.2,4.2,5.4,4.8,0.9,0.8,1.8,1.6,12.5,DPOY-6
3,4,Derrick White,29,SG,73,73,32.6,5.3,11.5,.461,...,0.7,3.5,4.2,5.2,1.0,1.2,1.5,2.1,15.2,DPOY-8
4,5,Kristaps PorziÅÄ£is,28,C,57,57,29.6,6.8,13.2,.516,...,1.7,5.5,7.2,2.0,0.7,1.9,1.6,2.7,20.1,
5,6,Al Horford,37,C,65,33,26.8,3.3,6.4,.511,...,1.3,5.1,6.4,2.6,0.6,1.0,0.7,1.4,8.6,
6,7,Payton Pritchard,26,PG,82,5,22.3,3.6,7.7,.468,...,0.9,2.4,3.2,3.4,0.5,0.1,0.7,1.3,9.6,
7,8,Sam Hauser,26,SF,79,13,22.0,3.2,7.1,.446,...,0.6,2.9,3.5,1.0,0.5,0.3,0.4,1.3,9.0,
8,9,Luke Kornet,28,C,63,7,15.6,2.3,3.2,.700,...,1.9,2.3,4.1,1.1,0.4,1.0,0.3,1.2,5.3,
9,10,Xavier Tillman Sr.,25,PF,20,2,13.7,1.7,3.3,.515,...,0.7,2.0,2.7,1.0,0.5,0.5,0.3,0.8,4.0,
10,11,Neemias Queta,24,C,28,0,11.9,2.4,3.7,.644,...,1.9,2.5,4.4,0.7,0.5,0.8,0.5,1.8,5.5,
11,12,Oshae Brissett,25,SF,55,1,11.5,1.2,2.8,.444,...,1.1,1.8,2.9,0.8,0.3,0.1,0.4,1.0,3.7,
12,13,Svi Mykhailiuk,26,SF,41,2,10.1,1.4,3.3,.416,...,0.3,1.0,1.2,0.9,0.3,0.0,0.3,0.5,4.0,
13,14,Jordan Walsh,19,SF,9,1,9.2,0.7,1.7,.400,...,0.6,1.7,2.2,0.6,0.6,0.1,0.3,1.2,1.7,
14,15,Drew Peterson,24,PF,3,0,7.7,1.3,2.0,.667,...,0.0,0.3,0.3,0.3,0.7,0.0,0.3,0.3,3.7,
15,16,Jaden Springer,21,SG,17,1,7.6,0.8,1.8,.433,...,0.5,0.7,1.2,0.5,0.6,0.2,0.5,1.0,2.1,
16,17,Dalano Banton,24,PG,24,1,7.1,0.8,2.1,.373,...,0.5,1.0,1.5,0.8,0.2,0.1,0.4,0.8,2.3,
17,18,Lamar Stevens,26,PF,19,1,6.4,1.1,2.4,.467,...,0.6,1.0,1.6,0.4,0.3,0.3,0.5,0.7,2.8,
18,19,JD Davison,21,SG,8,0,4.9,0.6,1.5,.417,...,0.3,1.0,1.3,1.3,0.1,0.1,0.3,0.5,2.0,
19,,Team Totals,,,82,82,241.8,43.9,90.2,.487,...,10.7,35.6,46.3,26.9,6.8,6.6,11.9,16.2,120.6,

In [108]:
df.to_csv(r'C:\Users\jadri\OneDrive\Documents\CSV\Basket.csv', index=False)